### ISSUE TITLE
Anyway to run 256x256 on 16 GB

### ISSUE THREAD

**Issue by nitinmukesh** [Hanbo-Cheng/DAWN-pytorch#10]
By offloading some models on CPU or reduce batch size. Any suggestions

**Comment by cleverpal-ai** [comment]
I cannot even run it on RTX4090 24GB

```
sampling loop time step:   0%|                      | 0/20 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "./DM_3/test_demo/test_VIDEO_hdtf_df_wpose_face_cond_init_ca_newae_ood_256_2.py", line 339, in <module>
    main()
  File "./DM_3/test_demo/test_VIDEO_hdtf_df_wpose_face_cond_init_ca_newae_ood_256_2.py", line 269, in main
    sample_output_dict = model.sample_one_video(sample_img=image_tensor.unsqueeze(dim=0).cuda()/255.,
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_model_multiGPU_v0_crema_vgg_floss_plus_faceemb_flow_fast_init_cond_test.py", line 358, in sample_one_video
    pred = self.diffusion.sample(sample_img_fea, bbox_mask, cond=ref_text,
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 1152, in sample
    return sample_fn(fea, (batch_size, channels, num_frames, fea.shape[-1], fea.shape[-1]), cond=cond,
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 1176, in ddim_sample
    pred_noise = self.denoise_fn.forward_with_cond_scale(
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 885, in forward_with_cond_scale
    logits = self.forward(*args, null_cond_prob=0., **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 913, in forward
    x = self.init_temporal_attn(x, pos_bias=time_rel_pos_bias)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 147, in forward
    return self.fn(x, *args, **kwargs) + x
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 213, in forward
    return self.fn(x, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 643, in forward
    x = self.fn(x, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/max/python_stuff/DAWN-pytorch/DM_3/modules/video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test.py", line 697, in forward
    sim = einsum('... h i d, ... h j d -> ... h i j', q, k)
  File "/home/max/python_stuff/DAWN-pytorch/DAWN/lib/python3.8/site-packages/torch/functional.py", line 377, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.52 GiB. GPU 0 has a total capacty of 23.99 GiB of which 4.01 GiB is free. Process 1 has 17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 16.46 GiB is allocated by PyTorch, and 1.15 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Hanbo-Cheng** [comment]
As mentioned in README, equipment, changing `DM_3\modules\video_flow_diffusion_model_multiGPU_v0_crema_vgg_floss_plus_faceemb_flow_fast_init_cond_test.py` line 8 to:
```
from DM_3.modules.video_flow_diffusion_multiGPU_v0_crema_plus_faceemb_ca_multi_test_local_opt import DynamicNfUnet3D, DynamicNfGaussianDiffusion
```
This will help a lot. You can also generate shorter video by changing `DM_3\test_demo\test_VIDEO_hdtf_df_wpose_face_cond_init_ca_newae_ood_256_2.py` line34, the value of `MAX_N_FRAMES` .

**Comment by nitinmukesh** [comment]
@Hanbo-Cheng 
Awesome m8. This (256x256) worked on 8 GB VRAM and with 8GB shared I am able to generate 5s even though processing time increase significantly which is understood.

I know I am asking for too much but any possibility to add batch generation otherwise I will have to split 2-2s audio and do generation.

**Comment by Hanbo-Cheng** [comment]
Indeed, this is one of the major limitations of this work, which I plan to solve in my next work. I tried to hardcode the local attention as a CUDA program but I encountered too many bugs to fix them 😅.  Anyway, I'll keep trying in the future.

**Comment by nitinmukesh** [comment]
Thank you @Hanbo-Cheng

**Comment by fanfanffff1** [comment]
Hello
There seems to  be no folder named **/DM_3/test_demo** . How can I get that？
