### ISSUE TITLE
soundfile.LibsndfileError: Error opening 'C:\\ai\\DAWN-pytorch\\tmph3p1humv.wav': System error.

### ISSUE THREAD

**Issue by nitinmukesh** [Hanbo-Cheng/DAWN-pytorch#4]
```
(DAWN) C:\ai\DAWN-pytorch>run_ood_test\run_DM_v0_df_test_128_both_pose_blink.bat
C:\ai\DAWN-pytorch\extract_init_states
C:\Users\nitin\miniconda3\envs\3DDFA\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
C:\ai\DAWN-pytorch
Loading the Wav2Vec2 Processor...
Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize
Ignored unknown kwarg option normalize
Loading the HuBERT Model...
2024-11-10 18:24:39.402411: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

TFHubertModel has backpropagation operations that are NOT supported on CPU. If you wish to train/fine-tune this model, you need a GPU or a TPU
2024-11-10 18:24:39.819035: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x24b49f60f70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-11-10 18:24:39.819271: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-11-10 18:24:39.830553: I .\tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
All TF 2.0 model weights were used when initializing HubertModel.

All the weights of HubertModel were initialized from the TF 2.0 model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use HubertModel for predictions without further training.
ffmpeg version 6.1-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[aist#0:0/pcm_s16le @ 00000224bdbf9940] Guessed Channel Layout: mono
Input #0, wav, from 'WRA_MarcoRubio_000.wav':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:00:21.01, bitrate: 256 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s16, 256 kb/s
File 'C:\ai\DAWN-pytorch\tmph3p1humv.wav' already exists. Overwrite? [y/N] y
[out#0/wav @ 00000224bdbf9240] Error opening output C:\ai\DAWN-pytorch\tmph3p1humv.wav: Permission denied
Error opening output file C:\ai\DAWN-pytorch\tmph3p1humv.wav.
Error opening output files: Permission denied
Traceback (most recent call last):
  File "hubert_extract\data_gen\process_lrs3\process_audio_hubert_interpolate_demo.py", line 135, in <module>
    speech_16k, _ = sf.read(output_wav_path.name)
  File "C:\Users\nitin\miniconda3\envs\DAWN\lib\site-packages\soundfile.py", line 285, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\Users\nitin\miniconda3\envs\DAWN\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\nitin\miniconda3\envs\DAWN\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\ai\\DAWN-pytorch\\tmph3p1humv.wav': System error.
```

**Comment by Hanbo-Cheng** [comment]
The "tempfile" package will incur the read and write permissions issue of files in Windows system. A alternative solution in `process_audio_hubert_interpolate_demo.py`:
```
if __name__ == '__main__':

    args = get_arguments()
    wav_path = args.src_audio_path
    wav_16k_name = wav_path
    npy_name = args.save_path

    # output_wav_path = tempfile.NamedTemporaryFile('w', suffix='.wav', dir='./')
    # convert_wav_to_16k(wav_path, output_wav_path.name)

    # speech_16k, _ = sf.read(output_wav_path.name)
    # delete_file(output_wav_path.name)

    speech_16k, _ = sf.read(wav_path)
```
Please make sure the audio file `wav_path`  has the sampling rate of 16K (`WRA_MarcoRubio_000.wav` has the 16K sampling rate, so you can try this file directly).

**Comment by nitinmukesh** [comment]
This fixed the problem. Thanks.
